/*
Softcare Information System
TINFO 360 B
Bikramjeet Ghura, Sheikh Jobe, Julian Galvan, Joe Phouapha
 */

package sofcare;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.Writer;
import java.time.LocalDateTime;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Sheikh
 */

// This is the ADL Chart that is used to chart patient diagnosis data.
public class ADLChart extends javax.swing.JFrame {
    static String PatientID;
    static String BedMobility;
    static String Transfer;
    static String EatingDrinking;
    static String Toileting;
    static String PersonalHygiene;
    static String Dressing;
    static String Bathing;
    static String WalkInRoom;
    static String WalkInHallway;
    static String LocomotionOnUnit;
    static String LocomotionOffUnit;
    static String PatientMood;
    /**
     * Creates new form ADLs
     */
    
    // ADLChart Object
    public ADLChart() {
        PatientID = null;
        BedMobility = null;
        Transfer = null;
        EatingDrinking = null;
        Toileting = null;
        PersonalHygiene = null;
        Dressing = null;
        Bathing = null;
        WalkInRoom = null;
        WalkInHallway = null;
        LocomotionOnUnit = null;
        LocomotionOffUnit = null;
        PatientMood = null;
        initComponents();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        taskLimitations = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        taskLimitations1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        taskLimitations2 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        taskLimitations3 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        taskLimitations4 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        taskLimitations5 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        taskLimitations6 = new javax.swing.JComboBox();
        taskLimitations7 = new javax.swing.JComboBox();
        taskLimitations8 = new javax.swing.JComboBox();
        taskLimitations9 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        taskLimitations10 = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        taskLimitations11 = new javax.swing.JComboBox();
        submitAdl = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PATIENT ADLs");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("PATIENT ADL CHARTING");

        taskLimitations.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        taskLimitations.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Record", "Independent", "Supervision", "Limited Assistance", "Extensive Assistance", "Total Assistance", "Extensive Assistance", "Activity did not occur" }));
        taskLimitations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskLimitationsActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("BED MOBILITY");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("TRANSFER");

        taskLimitations1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        taskLimitations1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Record", "Independent", "Supervision", "Limited Assistance", "Extensive Assistance", "Total Assistance", "Extensive Assistance", "Activity did not occur" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("EATING/DRINKING");

        taskLimitations2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        taskLimitations2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Record", "Independent", "Supervision", "Limited Assistance", "Extensive Assistance", "Total Assistance", "Extensive Assistance", "Activity did not occur" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("TOILETING");

        taskLimitations3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        taskLimitations3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Record", "Independent", "Supervision", "Limited Assistance", "Extensive Assistance", "Total Assistance", "Extensive Assistance", "Activity did not occur" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("PERSONAL HYGIENE");

        taskLimitations4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        taskLimitations4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Record", "Independent", "Supervision", "Limited Assistance", "Extensive Assistance", "Total Assistance", "Extensive Assistance", "Activity did not occur" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("DRESSING");

        taskLimitations5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        taskLimitations5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Record", "Independent", "Supervision", "Limited Assistance", "Extensive Assistance", "Total Assistance", "Extensive Assistance", "Activity did not occur" }));
        taskLimitations5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskLimitations5ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("BATHING");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("WALK IN ROOM");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("WALK IN HALLWAY");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("LOCOMOTION ON UNIT");

        taskLimitations6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        taskLimitations6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Record", "Independent", "Supervision", "Limited Assistance", "Extensive Assistance", "Total Assistance", "Extensive Assistance", "Activity did not occur" }));
        taskLimitations6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskLimitations6ActionPerformed(evt);
            }
        });

        taskLimitations7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Record", "Independent", "Supervision", "Limited Assistance", "Extensive Assistance", "Total Assistance", "Extensive Assistance", "Activity did not occur" }));

        taskLimitations8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        taskLimitations8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Record", "Independent", "Supervision", "Limited Assistance", "Extensive Assistance", "Total Assistance", "Extensive Assistance", "Activity did not occur" }));

        taskLimitations9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        taskLimitations9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Record", "Independent", "Supervision", "Limited Assistance", "Extensive Assistance", "Total Assistance", "Extensive Assistance", "Activity did not occur" }));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("LOCOMOTION OFF UNIT");

        taskLimitations10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        taskLimitations10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Record", "Independent", "Supervision", "Limited Assistance", "Extensive Assistance", "Total Assistance", "Extensive Assistance", "Activity did not occur" }));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("PATIENT MOOD");

        taskLimitations11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        taskLimitations11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Record", "Good", "Average", "Bad", "Combative" }));

        submitAdl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submitAdl.setText("SAVE");
        submitAdl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitAdlActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("LOGOUT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("VIEW PATIENTS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LookupPatient(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("GENERATE REPORT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenReport(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(taskLimitations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taskLimitations10, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(taskLimitations7, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(taskLimitations6, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(taskLimitations4, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(taskLimitations2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(65, 65, 65))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(submitAdl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(taskLimitations9, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(taskLimitations3, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(taskLimitations5, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(taskLimitations1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(taskLimitations8, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(taskLimitations11, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton3))
                .addGap(168, 168, 168))
            .addGroup(layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taskLimitations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taskLimitations1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taskLimitations3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taskLimitations2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taskLimitations4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taskLimitations5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taskLimitations6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taskLimitations8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(taskLimitations9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taskLimitations7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(taskLimitations10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taskLimitations11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitAdl)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void taskLimitations6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskLimitations6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taskLimitations6ActionPerformed

    private void taskLimitations5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskLimitations5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taskLimitations5ActionPerformed
    
    // Saves the ADL Data to the patient's individual text file in the ADL 
    // directory.
    private void submitAdlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitAdlActionPerformed
        // Displays the adl chart selection:
        BedMobility = taskLimitations.getSelectedItem().toString();
        Transfer = taskLimitations1.getSelectedItem().toString();
        EatingDrinking = taskLimitations2.getSelectedItem().toString();
        Toileting = taskLimitations3.getSelectedItem().toString();
        PersonalHygiene = taskLimitations4.getSelectedItem().toString();
        Dressing = taskLimitations5.getSelectedItem().toString();
        Bathing = taskLimitations6.getSelectedItem().toString();
        WalkInRoom = taskLimitations7.getSelectedItem().toString();
        WalkInHallway  = taskLimitations8.getSelectedItem().toString();
        LocomotionOnUnit = taskLimitations9.getSelectedItem().toString();
        LocomotionOffUnit = taskLimitations10.getSelectedItem().toString();
        PatientMood = taskLimitations11.getSelectedItem().toString();
        JOptionPane.showMessageDialog(this, "BED MOBILITY: " + BedMobility + "\n"  +
                "TRANSFER: " + Transfer + "\n" + "EATING/DRINKING: " + EatingDrinking + "\n" + 
                "TOILETING: " + Toileting + "\n" + "PERSONAL HYGIENE: " + PersonalHygiene + "\n" +
                "DRESSING: " + Dressing + "\n" + "BATHING: " + Bathing + "\n" + "WALK IN ROOM: " + 
                WalkInRoom + "\n" + "WALK IN HALLWAY: " + WalkInHallway + "\n" + "LOCOMOTION ON UNIT: " +
                LocomotionOnUnit + "\n" + "LOCOMOTION OFF UNIT: " + LocomotionOffUnit + "\n" +
                "PATIENT MOOD: " + PatientMood);
        PrintWriter writer = null;
        try {
            writer = new PrintWriter(new File("/Users/Bikramjeet/Documents/UW/Aut2016/TINFO360/Softcare/Updated/SofcareProject/SofCare/DataFiles/ADLs/" + PatientID + ".txt"));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ADLChart.class.getName()).log(Level.SEVERE, null, ex);
        }
        writer.println(BedMobility);
        writer.println(Transfer);
        writer.println(EatingDrinking);
        writer.println(Toileting);
        writer.println(PersonalHygiene);
        writer.println(Dressing);
        writer.println(Bathing);
        writer.println(WalkInRoom);
        writer.println(WalkInHallway);
        writer.println(LocomotionOnUnit);
        writer.println(LocomotionOffUnit);
        writer.println(PatientMood);
        writer.close();
        addPatientModification(PatientID, Employee.UserName, LocalDateTime.now().toString());
        JFrame frame = new JFrame("Save Dialog");
        JOptionPane.showMessageDialog(frame, "Save Successful!");
    }//GEN-LAST:event_submitAdlActionPerformed
    
    // Closes Window to show Patient List
    private void LookupPatient(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LookupPatient
        this.setVisible(false);
        PatientList.main(new String[] {"123"});
    }//GEN-LAST:event_LookupPatient
    
    // Takes back to login.
    private void Logout(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout
        this.setVisible(false);
        new Employee().setVisible(true);
    }//GEN-LAST:event_Logout

    private void taskLimitationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskLimitationsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taskLimitationsActionPerformed
    
    // Creates and saves a .txt report for the patient in the Reports directory.
    // Report takes in data from patient's general data/admissions .txt file and 
    // the ADL file.
    private void GenReport(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenReport
        PrintWriter writer = null;
        Scanner console = null;
        try {
            console = new Scanner(new File("/Users/Bikramjeet/Documents/UW/Aut2016/TINFO360/Softcare/Updated/SofcareProject/SofCare/DataFiles/Patients/" + PatientID + ".txt"));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ADLChart.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            // TODO add your handling code here:
            writer = new PrintWriter(new File("/Users/Bikramjeet/Documents/UW/Aut2016/TINFO360/Softcare/Updated/SofcareProject/SofCare/DataFiles/Reports/" + PatientID + ".txt"));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ADLChart.class.getName()).log(Level.SEVERE, null, ex);
        }
        writer.println("GENERAL INFORMATION:");
        writer.println("Patient ID: " + console.nextLine());
        writer.println("Name: " + console.nextLine() + " " + console.nextLine() + " " + console.nextLine());
        writer.println("Date of Birth: " + console.nextLine());
        console.nextLine();
        writer.println("Gender: " + console.nextLine());
        writer.println("==================================================");
        writer.println();
        writer.println("ACTIVITIES OF DAILY LIVING (ADL) DATA:");
        writer.println("Bed Mobility: " + BedMobility);
        writer.println("Transfer: " + Transfer);
        writer.println("Eating/Drinking: " + EatingDrinking);
        writer.println("Toileting: " + Toileting);
        writer.println("Personal Hygiene: " + PersonalHygiene);
        writer.println("Dressing: " + Dressing);
        writer.println("Bathing: " + Bathing);
        writer.println("Walk In Room: " + WalkInRoom);
        writer.println("Walk In Hallway: " + WalkInHallway);
        writer.println("Locomotion On Unit: " + LocomotionOnUnit);
        writer.println("Locomotion Off Unit: " + LocomotionOffUnit);
        writer.println("Patient Mood: " + PatientMood);
        writer.println("==================================================");
        console.close();
        writer.close();
        JFrame frame = new JFrame("Report Saved");
        JOptionPane.showMessageDialog(frame, "Report Generated!");
    }//GEN-LAST:event_GenReport
    
    // Loads an existing patient's ADL.
    public static void loadADL(String pID) {
        File pAdl = new File("/Users/Bikramjeet/Documents/UW/Aut2016/TINFO360/Softcare/Updated/SofcareProject/SofCare/DataFiles/ADLs/" + pID + ".txt");
        PatientID = pID;
        if(pAdl.exists()) {
            Scanner console = null;
            try {
                console = new Scanner(pAdl);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(ADLChart.class.getName()).log(Level.SEVERE, null, ex);
            }
            taskLimitations.setSelectedItem(console.nextLine());
            taskLimitations1.setSelectedItem(console.nextLine());
            taskLimitations2.setSelectedItem(console.nextLine());
            taskLimitations3.setSelectedItem(console.nextLine());
            taskLimitations4.setSelectedItem(console.nextLine());
            taskLimitations5.setSelectedItem(console.nextLine());
            taskLimitations6.setSelectedItem(console.nextLine());
            taskLimitations7.setSelectedItem(console.nextLine());
            taskLimitations8.setSelectedItem(console.nextLine());
            taskLimitations9.setSelectedItem(console.nextLine());
            taskLimitations10.setSelectedItem(console.nextLine());
            taskLimitations11.setSelectedItem(console.nextLine());
            CreateADLObject();
        }
    }
    
    // Sets all input field values to the ADL chart's attributes.
    public static void CreateADLObject() {
        BedMobility = taskLimitations.getSelectedItem().toString();
        Transfer = taskLimitations1.getSelectedItem().toString();
        EatingDrinking = taskLimitations2.getSelectedItem().toString();
        Toileting = taskLimitations3.getSelectedItem().toString();
        PersonalHygiene = taskLimitations4.getSelectedItem().toString();
        Dressing = taskLimitations5.getSelectedItem().toString();
        Bathing = taskLimitations6.getSelectedItem().toString();
        WalkInRoom = taskLimitations7.getSelectedItem().toString();
        WalkInHallway  = taskLimitations8.getSelectedItem().toString();
        LocomotionOnUnit = taskLimitations9.getSelectedItem().toString();
        LocomotionOffUnit = taskLimitations10.getSelectedItem().toString();
        PatientMood = taskLimitations11.getSelectedItem().toString();
    }
    
    // Adds the data about a patient ADL data modification event to 
    // PatientADLModification.txt.
    // Data added contains the username of the employee who modified the data,
    // the ID of the patient of whose data was modified, and the time of the 
    // day the modification was made.
    public void addPatientModification(String pat_ID, String emp_username, String time) {
        Writer output = null;
        try {
            output = new BufferedWriter(new FileWriter("/Users/Bikramjeet/Documents/UW/Aut2016/TINFO360/Softcare/Updated/SofcareProject/SofCare/DataFiles/PatientADLModification.txt", true));
        } catch (IOException ex) {
            Logger.getLogger(ADLChart.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            output.append(pat_ID + " " + emp_username + " " + time + "\n");
        } catch (IOException ex) {
            Logger.getLogger(ADLChart.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            output.close();
        } catch (IOException ex) {
            Logger.getLogger(ADLChart.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADLChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADLChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADLChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADLChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADLChart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton submitAdl;
    private static javax.swing.JComboBox taskLimitations;
    private static javax.swing.JComboBox taskLimitations1;
    private static javax.swing.JComboBox taskLimitations10;
    private static javax.swing.JComboBox taskLimitations11;
    private static javax.swing.JComboBox taskLimitations2;
    private static javax.swing.JComboBox taskLimitations3;
    private static javax.swing.JComboBox taskLimitations4;
    private static javax.swing.JComboBox taskLimitations5;
    private static javax.swing.JComboBox taskLimitations6;
    private static javax.swing.JComboBox taskLimitations7;
    private static javax.swing.JComboBox taskLimitations8;
    private static javax.swing.JComboBox taskLimitations9;
    // End of variables declaration//GEN-END:variables
}
